-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2024-02-12 19:28:40 EET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE attendance (
    id         INTEGER NOT NULL,
    skipreason NVARCHAR2(2000),
    status     SMALLINT NOT NULL,
    student_id INTEGER,
    lecture_id SMALLINT
);

COMMENT ON COLUMN attendance.status IS
    '1 - Neapmeklēts, 2 - Apmeklēts, 3 - Attaisnots';

ALTER TABLE attendance ADD CONSTRAINT attendance_pk PRIMARY KEY ( id );

CREATE TABLE course (
    id                INTEGER NOT NULL,
    name              NVARCHAR2(200) NOT NULL,
    lecturer_id       INTEGER NOT NULL,
    registerminutes   INTEGER NOT NULL,
    minimumattendance SMALLINT
);

ALTER TABLE course ADD CONSTRAINT course_pk PRIMARY KEY ( id );

CREATE TABLE lecture (
    id             SMALLINT NOT NULL,
    starttime      DATE NOT NULL,
    endtime        DATE NOT NULL,
    "Comment"      VARCHAR2(2000),
    course_id      INTEGER NOT NULL,
    mandatory      SMALLINT NOT NULL,
    attendancecode INTEGER NOT NULL
);

COMMENT ON COLUMN lecture.mandatory IS
    '0 - neobligāta lekcija, 1 - obligāta lekcija';

ALTER TABLE lecture ADD CONSTRAINT lecture_pk PRIMARY KEY ( id );

CREATE TABLE student_course (
    id         INTEGER NOT NULL,
    course_id  INTEGER,
    student_id INTEGER
);

ALTER TABLE student_course ADD CONSTRAINT student_course_pk PRIMARY KEY ( id );

CREATE TABLE "User" (
    id       INTEGER NOT NULL,
    username VARCHAR2(200) NOT NULL,
    password VARCHAR2(256) NOT NULL,
    type     SMALLINT NOT NULL,
    email    VARCHAR2(200) NOT NULL
);

COMMENT ON COLUMN "User".type IS
    '1 - students, 2 - pasniedzejs';

CREATE INDEX user__idx ON
    "User" (
        id
    ASC,
        username
    ASC );

ALTER TABLE "User" ADD CONSTRAINT user_pk PRIMARY KEY ( id );

ALTER TABLE "User" ADD CONSTRAINT user__un UNIQUE ( username );

CREATE TABLE usersettings (
    user_id        INTEGER NOT NULL,
    warnunattended SMALLINT,
    sendstatistic  SMALLINT
);

COMMENT ON COLUMN usersettings.warnunattended IS
    '1 - sūtīt paziņojumu par neapmeklētu lekciju, 0 - nesūtīt';

COMMENT ON COLUMN usersettings.sendstatistic IS
    '1 - sūtīt statistiku pēc lekcijas, 0 - nesūtīt';

ALTER TABLE usersettings ADD CONSTRAINT usersettings_pk PRIMARY KEY ( user_id );

ALTER TABLE attendance
    ADD CONSTRAINT attendance_lecture_fk FOREIGN KEY ( lecture_id )
        REFERENCES lecture ( id );

ALTER TABLE attendance
    ADD CONSTRAINT attendance_user_fk FOREIGN KEY ( student_id )
        REFERENCES "User" ( id );

ALTER TABLE lecture
    ADD CONSTRAINT lecture_course_fk FOREIGN KEY ( course_id )
        REFERENCES course ( id );

ALTER TABLE course
    ADD CONSTRAINT lecturer_user_fk FOREIGN KEY ( lecturer_id )
        REFERENCES "User" ( id );

ALTER TABLE student_course
    ADD CONSTRAINT student_course_course_fk FOREIGN KEY ( course_id )
        REFERENCES course ( id );

ALTER TABLE student_course
    ADD CONSTRAINT student_course_user_fk FOREIGN KEY ( student_id )
        REFERENCES "User" ( id );

ALTER TABLE usersettings
    ADD CONSTRAINT usersettings_user_fk FOREIGN KEY ( user_id )
        REFERENCES "User" ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
